### ISSUE TITLE
Allow prefixes longer than 1 char

### ISSUE THREAD

**Issue by MicaelJarniac** [FragLand/terracord#108]
### Expected Behavior
* Having a prefix like `t!`, `tc!` or similar should be possible, as to avoid conflicts with other prefixes. Many Discord bots do this by default nowadays.

### Actual Behavior/Symptoms
* Having a prefix that's not exactly 1 char causes the server to crash at startup.

### How to Reproduce Behavior/Symptoms
* Set the prefix to anything longer than a single char and try to start the server.

### Terracord Version
* `1.2.0`

### Terraria/TShock Version
* `4.4.0_Pre13`

### Discord.Net Version
* The one that comes bundled, `2.1.1` I think

### .NET/Mono Version
* No idea

### Operating System
* Windows 10 64bit

### Output/Screenshot(s)
Logs:
`[11/08/2020 20:54:22 -03:00] [Error] Unable to parse terracord.xml: String must be exactly one character long.`
<details>
<summary>Console</summary>

```
Error Logging Enabled.
TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.1.1 (233), OTAPI 1.4.1.1)
Terracord: [11/08/2020 20:54:22 -03:00] [Error] Unable to parse terracord.xml: String must be exactly one character long.
[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Failed to load assembly "Terracord.dll". ---> System.InvalidOperationException: Could not create an instance of plugin class "FragLand.TerracordPlugin.Terracord". ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: String must be exactly one character long.
   at System.Char.Parse(String s)
   at FragLand.TerracordPlugin.Config.Parse()
   at FragLand.TerracordPlugin.Terracord..ctor(Main game)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 316
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 324
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 333
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 117
   at TerrariaApi.Server.HookManager.InitialiseAPI() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HookManager.cs:line 27
```
</details>

**Comment by ldilley** [comment]
Removed the `bug` label as this behavior was the intended design. A single character is expected per `Config.cs`:

```cs
CommandPrefix =  char.Parse(configOptions.Element("command").Attribute("prefix").Value.ToString(Locale));
```

Any command prefix value longer than 1 character will trigger an exception which is expected. This request should be an `enhancement` instead since we want to expand the functionality of an existing feature.

I've no problem parsing strings instead of a single character for the command prefix. However, we need to also review how chat/commands are handled since this modification will likely have side effects on that code.

**Comment by ldilley** [comment]
The feature you requested has been added (ec136e1), @MicaelJarniac. Please let me know if you need anything else.

**Comment by MicaelJarniac** [comment]
> Removed the `bug` label as this behavior was the intended design. A single character is expected per `Config.cs`

Oh, sorry, I was unsure whether it was by design or not, so I ended up reporting as a bug.

>The feature you requested has been added

Awesome, thanks a lot!
