### ISSUE TITLE
401: Unauthorized error on startup

### ISSUE THREAD

**Issue by catqueen0124** [FragLand/terracord#147]
I'm certain the token in the xml is correct but upon startup I receive the following:

```Terracord: [05/12/2021 20:01:05 -04:00] [Warning] 20:01:05 Discord     A supplied token was invalid.:
System.ArgumentException: A Bot token must be at least 58 characters in length. Ensure that the Bot Token provided is not an OAuth client secret.
Parameter name: token
   at Discord.TokenUtils.ValidateToken(TokenType tokenType, String token)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
Terracord: [05/12/2021 20:01:06 -04:00] [Error] Unable to connect to Discord: The server responded with error 401: 401: Unauthorized
[Server API] Warning Plugin "Terracord" has had an unhandled exception thrown by one of its GamePostInitialize handlers:
Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__67`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetMyUserAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.DiscordRestClient.<OnLoginAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__96.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at FragLand.TerracordPlugin.Discord.<Connect>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at FragLand.TerracordPlugin.Terracord.OnPostInitialize(EventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HandlerCollection.cs:line 109```

**Comment by ldilley** [comment]
Greetings, @catqueen0124.

The symptom you encountered is a result of using the Discord.Net library with the Mono runtime. The aforementioned library does not support Mono. I'd recommend using .NET Framework >=4.7 as your runtime.

**Comment by catqueen0124** [comment]
How exactly do I change what runtime I'm using?

**Comment by ldilley** [comment]
What operating system are you using? If Windows, download and install the latest official .NET Framework from Microsoft here: https://dotnet.microsoft.com/download/dotnet-framework. If Linux, Mono 6.8 has been reported to work with `Terracord.dll` targeting `net46`.

**Comment by catqueen0124** [comment]
It has been fixed, thanks!
